app/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls import handler404
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from .sitemaps import StaticSitemap, ArticlesSitemap, CollaboratorsSitemap


sitemaps = {
    'static': StaticSitemap(),
    'articles': ArticlesSitemap(),
    'collaborators': CollaboratorsSitemap()
}


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(
        r'^robots\.txt$',
        TemplateView.as_view(
            template_name="robots.txt",
            content_type="text/plain"
        )
    ),
    re_path(
        r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('', include(('core.urls', 'core'), namespace='core')),
    # Apps
    path(
        'comunidad/',
        include(
            ('collaborators.urls', 'collaborators'), namespace='collaborators'
        )
    ),
    path(
        'blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('usuarios/', include('registration.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
]


handler404 = 'core.views.view_404'


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (
    ArticleListView, ArticleDetailView, ArticleCreate,
    ArticleUpdate, ArticleDelete)


urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('crear-nueva-entrada/', ArticleCreate.as_view(), name='create'),
    path(
        '<slug:publication_type>/',
        ArticleListView.as_view(), name='category'),
    path(
        '<slug:publication_type>/<slug:slug>/',
        ArticleDetailView.as_view(), name='article'
    ),
    path(
        '<slug:publication_type>/<slug:slug>/actualizar/',
        ArticleUpdate.as_view(), name='update'
    ),
    path('<slug:publication_type>/<slug:slug>/borrar/',
        ArticleDelete.as_view(), name='delete'
    ),
]

core/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('cms/<slug:slug>/', views.ContentManagment.as_view(), name='cms'),
]

templates/base/footer.html
{% load static %}

<footer class="footer">
  <div class="columns is-centered">
    <div class="column is-2">
      <figure class="image">
        <img src="{% static '/images/division-ciencias-tierra.png' %}">
      </figure>
    </div>

    <div class="column is-6 content is-small">
      <h2>Universidad Nacional Autónoma de México</h4>
      <p>División de Ingeniería en Ciencias de la Tierra.
        Universidad Nacional Autónoma de México.
        Facultad de Ingeniería, Edificio “A” Planta Baja,
        Av. Universidad 3000, Ciudad Universitaria,
        Delegación Coyoacán, México, Ciudad de México, Código Postal 04510.
        Horario de Atención:De 9:00 a 15:00 hrs. y de 17:00 a 21:00 hrs.
        De Lunes a Viernes.
      </p>
    </div>
    <div class="column is-2">
    </div>
  </div>
</footer>

templates/base/header.html
{% load static %}

<nav class="navbar is-black is-fixed-top">
  <div class="container">
    <div class="navbar-brand">
      <a class="navbar-item" href="{%url 'core:home'%}">
        <figure class="image">
          <img src="{% static '/images/division-ciencias-tierra.png' %}">
        </figure>
      </a>
      <span class="navbar-burger burger" data-target="navbarMenu">
        <span></span>
        <span></span>
        <span></span>
      </span>
    </div>
    <div id="navbarMenu" class="navbar-menu">
      <div class="navbar-end">
        <a class="navbar-item" href="/comunidad">
          Comunidad Académica
        </a>
        <a class="navbar-item" href="/blog">
          Todo
        </a>
        <a class="navbar-item" href="/blog/lecturas">
          Lecturas
        </a>
        <a class="navbar-item" href="/blog/videos">
          Videos
        </a>
        <a class="navbar-item" href="/blog/recursos-didacticos">
          Recursos Didácticos
        </a>
        <div class="navbar-item has-dropdown is-hoverable">
          <a class="navbar-link">
            Acceso
          </a>
          {% if user.is_authenticated %}
            <div class="navbar-dropdown">
              <a class="navbar-item" href="{% url 'my-profile' %}">
                Perfil
              </a>
              {% if user.profile.approved %}
              <a class="navbar-item" href="{% url 'blog:create' %}">
                Crear recurso
              </a>
              {% endif %}
              <hr class="navbar-divider">
              <div class="navbar-item">
                <div class="field is-grouped">
                  <p class="control">
                    <a class="button is-small" href="{% url 'logout' %}">
                      <span class="icon"><i class="fa fa-user-plus"></i></span>
                      <span>Cerrar sesión</span>
                    </a>
                  </p>
                </div>
              </div>
            {% else %}
              <div class="navbar-dropdown">
                <div class="navbar-item">
                  <div class="field is-grouped">
                    <p class="control">
                      <a class="button is-small" href="{% url 'sign-up'%}">
                          <span class="icon"><i class="fa fa-user-plus"></i></span>
                          <span>Registrarse</span>
                      </a>
                    </p>
                    <p class="control">
                      <a class="button is-small is-info is-outlined" href="{% url 'login'%}">
                        <span class="icon">
                            <i class="fa fa-user"></i>
                        </span>
                        <span>Login</span>
                      </a>
                    </p>
              </div>
            </div>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</nav>