app/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from django.conf import settings
from django.conf.urls import handler404
from django.contrib.sitemaps.views import sitemap
from django.views.generic.base import TemplateView

from .sitemaps import StaticSitemap, ArticlesSitemap, CollaboratorsSitemap


sitemaps = {
    'static': StaticSitemap(),
    'articles': ArticlesSitemap(),
    'collaborators': CollaboratorsSitemap()
}


urlpatterns = [
    path('admin/', admin.site.urls),
    re_path(
        r'^robots\.txt$',
        TemplateView.as_view(
            template_name="robots.txt",
            content_type="text/plain"
        )
    ),
    re_path(
        r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps},
        name='django.contrib.sitemaps.views.sitemap'
    ),
    path('', include(('core.urls', 'core'), namespace='core')),
    # Apps
    path(
        'comunidad/',
        include(
            ('collaborators.urls', 'collaborators'), namespace='collaborators'
        )
    ),
    path(
        'blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('usuarios/', include('registration.urls')),
    path('usuarios/', include('django.contrib.auth.urls')),
]


handler404 = 'core.views.view_404'


if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(
        settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from .views import (
    ArticleListView, ArticleDetailView, ArticleCreate,
    ArticleUpdate, ArticleDelete)


urlpatterns = [
    path('', ArticleListView.as_view(), name='articles'),
    path('crear-nueva-entrada/', ArticleCreate.as_view(), name='create'),
    path(
        '<slug:publication_type>/',
        ArticleListView.as_view(), name='category'),
    path(
        '<slug:publication_type>/<slug:slug>/',
        ArticleDetailView.as_view(), name='article'
    ),
    path(
        '<slug:publication_type>/<slug:slug>/actualizar/',
        ArticleUpdate.as_view(), name='update'
    ),
    path('<slug:publication_type>/<slug:slug>/borrar/',
        ArticleDelete.as_view(), name='delete'
    ),
]

collaborators/urls.py
from django.urls import path
from .views import CollaboratorListView, CollaboratorDetailView


urlpatterns = [
    path('', CollaboratorListView.as_view(), name='collaborators'),
    path(
        '<username>/', CollaboratorDetailView.as_view(), name='collaborator')
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Article(models.Model):

    class PublicationType(models.TextChoices):
        READS = "lecturas", "Lecturas"
        VIDEOS = "videos", "Videos"
        OTHER_RESOURCES = "recursos-didacticos", "Recursos Didácticos"
    
    def custom_uplad_to(instance, filename):
        if Article.objects.get(id=instance.id):
            old_instance = Article.objects.get(id=instance.id)
            old_instance.main_picture.delete()
        return 'resources/' + filename

    id = models.AutoField(primary_key=True)
    title = models.CharField(verbose_name="Título", max_length=200)
    main_picture = models.ImageField(
        upload_to=custom_uplad_to, verbose_name="Foto de portada",
        null=True, blank=True
    )
    slug = models.SlugField(max_length=250, unique=True)
    short_description = models.CharField(
        verbose_name='Descripción', null=False, max_length=300
    )
    publication_type = models.CharField(
        verbose_name='Tipo de publicación', null=False, max_length=20,
        choices=PublicationType.choices
    )
    resource_url = models.URLField(
        verbose_name="URL del recurso", null=False
    )
    subject = models.CharField(
        verbose_name='Temática', null=False, max_length=250
    )
    author = models.ForeignKey(
        User, on_delete=models.DO_NOTHING,
        verbose_name='Autor', null=False
    )
    created_at = models.DateTimeField(
        verbose_name="Fecha de creación", null=False,
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        verbose_name="Fecha de creación", null=False,
        auto_now=True
    )

    class Meta:
        verbose_name = "Recurso"
        verbose_name_plural = "Recursos"
        ordering = ['updated_at', 'title']

    def __str__(self):
        return self.title

blog/forms.py
from django import forms

from .models import Article


class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = (
            'title', 'short_description', 'publication_type',
            'subject', 'resource_url', 'main_picture'
        )

        widgets = {
            'title': forms.TextInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'Ej. Cuestionario de Meteorización'
                }
            ),
            'short_description': forms.Textarea(
                attrs={
                    'class': 'textarea',
                    'rows': 3,
                    'placeholder':
                        'Ej. En este cuestionario pondrás '
                        'a prueba tus conocimientos ...'
                }
            ),
            'publication_type': forms.Select(),
            'subject': forms.TextInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'Ej. Meteorización'
                }
            ),
            'resource_url': forms.URLInput(
                attrs={
                    'class': 'input',
                    'placeholder': 'Ej. https://ejemplo.com/cuestionario'}
            ),
            'main_picture': forms.ClearableFileInput(
                attrs={'class': 'file-input'}
            )
        }

blog/views.py
import random

from django.contrib.admin.views.decorators import staff_member_required
from django.http import Http404
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.utils.text import slugify
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView

from .models import Article
from .forms import ArticleForm
from core.views import WebsiteCommonMixin
from registration.decorators import is_approved, is_author


class ArticleListView(WebsiteCommonMixin, ListView):
    model = Article
    ordering = ['title']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        subject = Article.objects.order_by(
            'subject').values_list('subject', flat=True).distinct()

        context['subject'] = subject
        return context

    def get_queryset(self):
        articles = Article.objects.all()

        if self.kwargs.get('publication_type'):
            articles = articles.filter(
                publication_type=self.kwargs['publication_type'])
            if len(articles) == 0:
                raise Http404()

        return articles


class ArticleDetailView(WebsiteCommonMixin, DetailView):
    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = self.get_articles()
        context['is_author'] = self.check_author()

        return context

    def get_articles(self):
        articles = Article.objects.filter(
            author=self.object.author
        ).exclude(
            title=self.object.title
        )
        articles = list(articles)
        random.shuffle(articles)

        return articles
    
    def check_author(self):
        slug = self.request.resolver_match.kwargs['slug']
        author = str(Article.objects.filter(slug=slug)[0].author).strip()
        return author == self.request.user.username.strip()


@method_decorator(is_approved, name='dispatch')
class ArticleCreate(WebsiteCommonMixin, CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_form.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('blog:article', args=[
            self.object.publication_type, self.object.slug
        ]) + '?ok'


@method_decorator(is_author, name='dispatch')
class ArticleUpdate(WebsiteCommonMixin, UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'blog/article_form.html'

    def get_success_url(self):
        print('en la vista')
        return reverse_lazy('blog:update', args=[
            self.object.publication_type, self.object.slug
        ]) + '?ok'



@method_decorator(is_author, name='dispatch')
class ArticleDelete(WebsiteCommonMixin, DeleteView):
    model = Article
    success_url = reverse_lazy('blog:article')

templates/blog/article_detail.html
{% extends "index.html" %}

{% block title %} {{object.title}} {% endblock %}
{% block description %} {{object.short_description}} {% endblock %}

{% load static %}

{% block extra_styles %}
{% endblock %}


{% block content %}
<section class="section is-medium container" id="article-main-image">
  <div class="container column is-10">
    <article class="columns">
      <div class="column is-5">
        {% if object.main_picture %}
        <img
          style="height: 250px; display: flex; margin: auto;"
          src="{{object.main_picture.url}}"
        >
        {% else %}
        <div class="columns is-centered">
          <i class="fas fa-solid fa-newspaper fa-3x"></i>
        </div>
        {% endif %}
      </div>
      <div class="column is-5">
        <div>
          {% if is_author %}
            <a
              class="button is-small is-secundary"
              href="{% url 'blog:update' object.publication_type object.slug%}"
            >Editar</a> &nbsp; &nbsp; &nbsp; &nbsp;
            <a
              class="button is-small is-danger"
              href="{% url 'blog:delete' object.publication_type object.slug%}"
            >Borrar</a>
          <hr>
          {% endif %}
          <h3 class="heading">{{object.publication_type}} | {{object.subject}}</h3>
          <h1 class="title">{{object.title}}</h1>
          <h1 class="heading"> Por: 
            <a href="{% url 'collaborators:collaborator' object.author.username %}">
              {{object.author.first_name}} {{object.author.last_name}}
            </a>
          </h1>
          <p>{{object.short_description}}</p>
          <br>
          <a href="{{object.resource_url}}" class="button is-primary">Ir al recurso</a>
        </div>
      </div>
    </article>
  </div>
</section>
{% if articles %}
<hr>
<section class="section container">
  <h1 class="title">Más del autor</h1>
  <div class="columns is-10">
    {% for article in articles %}
     {% include 'blog/card.html' with article=article %}
    {% endfor %}
  </div>
</section>
{% endif %}
{% endblock %}

{% block extra_scripts %}
{% endblock %}

templates/blog/article_form.html
{% extends "index.html" %}

{% block title %} Crear entrada {% endblock %}

{% load static %}

{% block extra_styles %}
{% endblock %}

{% block content %}
<section class="hero is-fullheight" style="min-height: 75vh;">
  <div class="hero-body">
    <div class="container">
      <div class="column is-10 is-offset" style="margin: auto;">
        <h1 class="title">Crear o actualizar entrada</h1>
        <form action="" method="post" enctype="multipart/form-data"> {% csrf_token %}
          <div class="field">
            <label class="label">Título</label>
            <div class="control">
              {{form.title}}
            </div>
          </div>
          <div class="field">
            <label class="label">Slug</label>
            <div class="control">
              {{form.slug}}
            </div>
          </div>
          <div class="field">
            <label class="label">Descripción corta</label>
            <div class="control">
              {{form.short_description}}
            </div>
          </div>
          <div class="field field-body">
            <div class="field">
              <label class="label">Tipo de publicación</label>
              <div class="select">
                {{form.publication_type}}
              </div>
            </div>
            <div class="field">
              <label class="label">Temática</label>
              <div class="control">
                {{form.subject}}    
              </div>
            </div>
          </div>
          <div class="field">
            <label class="label">Url del recurso</label>
            <div class="control">
              {{form.resource_url}}
            </div>
          </div>
          {% if article.main_picture %}
          <img src="{{ article.main_picture.url }}" style="max-height: 200px;">
          <p class="mt-1">¿Borrar?
            <input type="checkbox" id="avatar-clear" name="avatar-clear"/>
          </p>
          {% endif %}
          <div class="file is-boxed" style="justify-content: center;">
            <label class="file-label">
              {{ form.main_picture }}
              <span class="file-cta">
                <span class="file-icon">
                  <i class="fas fa-upload"></i>
                </span>
                <span class="file-label">
                  Selecciona una imagen
                </span>
              </span>
            </label>
          </div>
          <br>
          <br>
          <div class="field is-grouped" style="justify-content: center;">
            <div class="control">
              <button class="button is-link is-light">Cancelar</button>
            </div>
            <div class="control">
              <button class="button is-link" type="submit">Crear o Actualizar</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>
{% endblock %}

templates/blog/article_list.html
{% extends "index.html" %}

{% block title %} Artículos {% endblock %}
{% block description %}Un listado de las entradas disponibles.{% endblock %}

{% load static %}

{% block extra_styles %}

{% endblock %}


{% block content %}
<section class="section is-medium container">
  <h1 class="title"> Listado de recursos disponibles.</h1>
  <br>
  <br>
  {% for article in article_list %}
  <div class="columns is-10 is-vcentered">
    <div class="column is-3">
      <a href="{% url 'blog:article' article.publication_type article.slug %}">
        {% if article.main_picture %}
        <img
          style="height: 200px; display: flex; margin: auto;"
          src="{{ article.main_picture.url }}"
        >
        {% else %}
        <div class="columns is-centered">
          <i class="fas fa-solid fa-newspaper fa-3x"></i>
        </div>
        {% endif %}
      </a>
    </div>
    <div class="column">
      <h3 class="heading">{{article.publication_type}} | {{article.subject}}</h3>
      <h1 class="title"> <a href="{% url 'blog:article' article.publication_type article.slug %}">{{article.title}}</a></h1>
      <h1 class="heading">Por:
        <a href="{% url 'collaborators:collaborator' article.author.username %}">
          {{article.author.first_name}} {{article.author.last_name}}
        </a>
      </h1>
      <p>{{article.short_description}}</p>
    </div>
  </div>
  <hr>
  {% endfor %}
</section>
{% endblock %}

{% block extra_scripts %}
{% endblock %}

templates/blog/card.html
<div class="column is-4">
  <article class="columns is-multiline">
    <div class="column is-12">
      {% if article.main_picture %}
      <img
        src="{{article.main_picture.url}}"
        style="max-height: 152px; margin: auto; display: flex;"
      >
      {% else %}
      <div class="columns is-centered">
        <i class="fas fa-solid fa-newspaper fa-3x"></i>
      </div>
      {% endif %}
    </div>
    <div class="column is-12 featured-content ">
      <h3 class="heading">{{article.publication_type}} | {{article.subject}}</h3>
      <h1 class="title">{{article.title}}</h1>
      <p>{{article.short_description}}</p>
      <br>
      <a
        href="{% url 'blog:article' article.publication_type article.slug %}"
        class="button is-primary"
      >Ver más</a>
    </div>
  </article>
</div>